---
language: ruby
sudo: false
bundler_args: --without development --jobs=3 --retry=3 --no-deployment
cache: bundler
script:
  - bundle exec rake test
notifications:
  email: false
matrix:
  fast_finish: true
  include:
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 3"
  - rvm: '2.1'
    env: PUPPET_VERSION="~> 4"
  - rvm: '2.3'
    env: PUPPET_VERSION="~> 3"
  - rvm: '2.3'
    env: PUPPET_VERSION="~> 4"
  - rvm: '2.4'
    env: PUPPET_VERSION="~> 3"
  - rvm: '2.4'
    env: PUPPET_VERSION="~> 4"
  - rvm: '2.4'
    sudo: required
    services: docker
    script: bundle exec rake beaker:centos-6-docker
  - rvm: '2.4'
    sudo: required
    services: docker
    script: bundle exec rake beaker:centos-7-docker
  - rvm: '2.4'
    sudo: required
    services: docker
    script: bundle exec rake beaker:ubuntu-14.04-docker
  - rvm: '2.4'
    sudo: required
    services: docker
    script: bundle exec rake beaker:ubuntu-16.04-docker
  - rvm: '2.4'
    sudo: required
    services: docker
    script: bundle exec rake beaker:debian-7-docker
  - rvm: '2.4'
    sudo: required
    services: docker
    script: bundle exec rake beaker:debian-8-docker
