---
language: ruby
sudo: false
bundler_args: --without development --jobs=3 --retry=3
cache: bundler
script:
  - bundle exec rake test
rvm:
  - '2.1'
  - '2.3'
  - '2.4'
notifications:
  email: false
